# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, exceptions, filepath, resourcet, tasty, tastyHunit
, transformers
}:

cabal.mkDerivation (self: {
  pname = "temporary-resourcet";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [ exceptions filepath resourcet transformers ];
  testDepends = [ resourcet tasty tastyHunit transformers ];
  meta = {
    homepage = "http://www.github.com/ttuegel/temporary-resourcet";
    description = "Portable temporary files and directories with automatic deletion";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
